# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_focusmap.ui'
#
# Created: Mon Dec  8 13:11:51 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FocusMap(object):
    def setupUi(self, FocusMap):
        FocusMap.setObjectName(_fromUtf8("FocusMap"))
        FocusMap.resize(467, 414)
        FocusMap.setMinimumSize(QtCore.QSize(467, 365))
        FocusMap.setMaximumSize(QtCore.QSize(467, 465))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        FocusMap.setFont(font)
        self.ChooseLayerButton = QtGui.QToolButton(FocusMap)
        self.ChooseLayerButton.setEnabled(True)
        self.ChooseLayerButton.setGeometry(QtCore.QRect(185, 120, 23, 25))
        self.ChooseLayerButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ChooseLayerButton.setArrowType(QtCore.Qt.RightArrow)
        self.ChooseLayerButton.setObjectName(_fromUtf8("ChooseLayerButton"))
        self.UnchooseLayerButton = QtGui.QToolButton(FocusMap)
        self.UnchooseLayerButton.setGeometry(QtCore.QRect(185, 170, 23, 25))
        self.UnchooseLayerButton.setArrowType(QtCore.Qt.LeftArrow)
        self.UnchooseLayerButton.setObjectName(_fromUtf8("UnchooseLayerButton"))
        self.label_FM = QtGui.QLabel(FocusMap)
        self.label_FM.setGeometry(QtCore.QRect(170, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.label_FM.setFont(font)
        self.label_FM.setObjectName(_fromUtf8("label_FM"))
        self.RasterLayers = QtGui.QListWidget(FocusMap)
        self.RasterLayers.setEnabled(True)
        self.RasterLayers.setGeometry(QtCore.QRect(15, 80, 161, 163))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RasterLayers.sizePolicy().hasHeightForWidth())
        self.RasterLayers.setSizePolicy(sizePolicy)
        self.RasterLayers.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RasterLayers.setFont(font)
        self.RasterLayers.setMidLineWidth(0)
        self.RasterLayers.setAutoScrollMargin(16)
        self.RasterLayers.setObjectName(_fromUtf8("RasterLayers"))
        self.ChosenLayers = QtGui.QListWidget(FocusMap)
        self.ChosenLayers.setGeometry(QtCore.QRect(215, 80, 161, 163))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ChosenLayers.setFont(font)
        self.ChosenLayers.setObjectName(_fromUtf8("ChosenLayers"))
        self.label_RL = QtGui.QLabel(FocusMap)
        self.label_RL.setGeometry(QtCore.QRect(14, 60, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_RL.setFont(font)
        self.label_RL.setObjectName(_fromUtf8("label_RL"))
        self.label_CL = QtGui.QLabel(FocusMap)
        self.label_CL.setGeometry(QtCore.QRect(214, 60, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_CL.setFont(font)
        self.label_CL.setObjectName(_fromUtf8("label_CL"))
        self.label_W = QtGui.QLabel(FocusMap)
        self.label_W.setGeometry(QtCore.QRect(390, 60, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_W.setFont(font)
        self.label_W.setObjectName(_fromUtf8("label_W"))
        self.fcomboBox = QtGui.QComboBox(FocusMap)
        self.fcomboBox.setGeometry(QtCore.QRect(20, 270, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fcomboBox.setFont(font)
        self.fcomboBox.setObjectName(_fromUtf8("fcomboBox"))
        self.fcomboBox.addItem(_fromUtf8(""))
        self.fcomboBox.addItem(_fromUtf8(""))
        self.CancelButton = QtGui.QPushButton(FocusMap)
        self.CancelButton.setGeometry(QtCore.QRect(230, 370, 98, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.OKButton = QtGui.QPushButton(FocusMap)
        self.OKButton.setGeometry(QtCore.QRect(340, 370, 98, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.OKButton.setFont(font)
        self.OKButton.setObjectName(_fromUtf8("OKButton"))
        self.lineEdit_w1 = QtGui.QLineEdit(FocusMap)
        self.lineEdit_w1.setGeometry(QtCore.QRect(385, 83, 71, 21))
        self.lineEdit_w1.setObjectName(_fromUtf8("lineEdit_w1"))
        self.lineEdit_w3 = QtGui.QLineEdit(FocusMap)
        self.lineEdit_w3.setGeometry(QtCore.QRect(385, 133, 71, 21))
        self.lineEdit_w3.setObjectName(_fromUtf8("lineEdit_w3"))
        self.lineEdit_w4 = QtGui.QLineEdit(FocusMap)
        self.lineEdit_w4.setGeometry(QtCore.QRect(385, 158, 71, 21))
        self.lineEdit_w4.setObjectName(_fromUtf8("lineEdit_w4"))
        self.lineEdit_w2 = QtGui.QLineEdit(FocusMap)
        self.lineEdit_w2.setGeometry(QtCore.QRect(385, 108, 71, 21))
        self.lineEdit_w2.setObjectName(_fromUtf8("lineEdit_w2"))
        self.Button_path = QtGui.QPushButton(FocusMap)
        self.Button_path.setGeometry(QtCore.QRect(340, 310, 81, 27))
        self.Button_path.setObjectName(_fromUtf8("Button_path"))
        self.lineEdit_outputpath = QtGui.QLineEdit(FocusMap)
        self.lineEdit_outputpath.setGeometry(QtCore.QRect(40, 310, 281, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_outputpath.setFont(font)
        self.lineEdit_outputpath.setObjectName(_fromUtf8("lineEdit_outputpath"))
        self.checkBox = QtGui.QCheckBox(FocusMap)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(20, 340, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setCheckable(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.lineEdit_w5 = QtGui.QLineEdit(FocusMap)
        self.lineEdit_w5.setGeometry(QtCore.QRect(385, 183, 71, 21))
        self.lineEdit_w5.setObjectName(_fromUtf8("lineEdit_w5"))
        self.lineEdit_w6 = QtGui.QLineEdit(FocusMap)
        self.lineEdit_w6.setGeometry(QtCore.QRect(385, 208, 71, 21))
        self.lineEdit_w6.setObjectName(_fromUtf8("lineEdit_w6"))
        self.pcomboBox = QtGui.QComboBox(FocusMap)
        self.pcomboBox.setGeometry(QtCore.QRect(220, 270, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pcomboBox.setFont(font)
        self.pcomboBox.setObjectName(_fromUtf8("pcomboBox"))
        self.pcomboBox.addItem(_fromUtf8(""))
        self.pcomboBox.addItem(_fromUtf8(""))
        self.pcomboBox.addItem(_fromUtf8(""))
        self.label_Focus = QtGui.QLabel(FocusMap)
        self.label_Focus.setGeometry(QtCore.QRect(20, 250, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Focus.setFont(font)
        self.label_Focus.setObjectName(_fromUtf8("label_Focus"))
        self.label_Re = QtGui.QLabel(FocusMap)
        self.label_Re.setGeometry(QtCore.QRect(220, 250, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Re.setFont(font)
        self.label_Re.setObjectName(_fromUtf8("label_Re"))
        self.logolabel = QtGui.QLabel(FocusMap)
        self.logolabel.setGeometry(QtCore.QRect(350, 10, 101, 21))
        self.logolabel.setText(_fromUtf8(""))
        self.logolabel.setPixmap(QtGui.QPixmap(_fromUtf8("sensum.png")))
        self.logolabel.setObjectName(_fromUtf8("logolabel"))
        self.helpButton = QtGui.QPushButton(FocusMap)
        self.helpButton.setGeometry(QtCore.QRect(20, 370, 98, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.helpButton.setFont(font)
        self.helpButton.setObjectName(_fromUtf8("helpButton"))

        self.retranslateUi(FocusMap)
        QtCore.QMetaObject.connectSlotsByName(FocusMap)

    def retranslateUi(self, FocusMap):
        FocusMap.setWindowTitle(QtGui.QApplication.translate("FocusMap", "FocusMap", None, QtGui.QApplication.UnicodeUTF8))
        self.ChooseLayerButton.setText(QtGui.QApplication.translate("FocusMap", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.UnchooseLayerButton.setText(QtGui.QApplication.translate("FocusMap", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_FM.setText(QtGui.QApplication.translate("FocusMap", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:400;\">Focus Map</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_RL.setText(QtGui.QApplication.translate("FocusMap", "Raster layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CL.setText(QtGui.QApplication.translate("FocusMap", "Chosen layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_W.setText(QtGui.QApplication.translate("FocusMap", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.fcomboBox.setItemText(0, QtGui.QApplication.translate("FocusMap", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.fcomboBox.setItemText(1, QtGui.QApplication.translate("FocusMap", "LogLinear", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelButton.setText(QtGui.QApplication.translate("FocusMap", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.OKButton.setText(QtGui.QApplication.translate("FocusMap", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.Button_path.setText(QtGui.QApplication.translate("FocusMap", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("FocusMap", "Add to canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.pcomboBox.setItemText(0, QtGui.QApplication.translate("FocusMap", "Highest", None, QtGui.QApplication.UnicodeUTF8))
        self.pcomboBox.setItemText(1, QtGui.QApplication.translate("FocusMap", "Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pcomboBox.setItemText(2, QtGui.QApplication.translate("FocusMap", "Lowest", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Focus.setText(QtGui.QApplication.translate("FocusMap", "Pooling Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Re.setText(QtGui.QApplication.translate("FocusMap", "Match Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("FocusMap", "Help", None, QtGui.QApplication.UnicodeUTF8))

